### ISSUE TITLE
Codec Bug

### ISSUE THREAD

**Issue by Julaja** [johndoe31415/pysuchsel#2]
Traceback (most recent call last):
  File "./pysuchsel", line 48, in <module>
    for line in f:
  File "/usr/lib/python3.6/codecs.py", line 321, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xe4 in position 6: invalid continuation byte

**Comment by Julaja** [comment]
[words.txt](https://github.com/johndoe31415/pysuchsel/files/3543148/words.txt)

**Comment by johndoe31415** [comment]
Thanks for the report. Unusual, some lines have CR/LF (Windows) line endings, others just LF. And the file seems to be ISO8859 instead of UTF-8. Please try one of the following:

* On the commandline you could do "recode lat1..utf-8 words.txt"
* When using an editor like pluma, do "Save as..." and on the bottom left comobox select "UTF-8" as the codec.

Please then try again and report back if it's fixed! Thanks!

**Comment by johndoe31415** [comment]
Issue is fixed.
